# Generated by Django 4.2.9 on 2024-07-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titlename', models.CharField(max_length=50)),
                ('Authorname', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Publisheddate', models.DateField()),
            ],
        ),
    ]
